
#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes { MYMACRO_AO = SAFE_RANGE, MYMACRO_OES, MYMACRO_CAO, MYMACRO_COES, MYMACRO_MAIL };


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_2(LT(8,KC_Q), KC_W, KC_F, KC_P, OS_LSFT, OS_RSFT, KC_L, KC_U, KC_Y, LT(8,KC_K), LSFT_T(KC_D), LCTL_T(KC_S), LALT_T(KC_A), LGUI_T(KC_R), HYPR_T(KC_C), KC_M, KC_N, RALT_T(KC_E), RCTL_T(KC_I), RSFT_T(KC_O), LT(6,KC_V), KC_G, KC_X, KC_T, KC_DEL, KC_ESC, KC_H, KC_B, KC_J, LT(7,KC_Z), LT(2,KC_SPC), LT(3,KC_TAB), LT(5,KC_ENT), LT(4,KC_BSPC)),
    [1] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_F, KC_P, OS_LSFT, OS_RSFT, KC_L, KC_U, KC_Y, KC_K, KC_D, KC_S, KC_A, KC_R, KC_C, KC_M, KC_N, KC_E, KC_I, KC_O, KC_V, KC_G, KC_X, KC_T, KC_DEL, TO(0), KC_H, KC_B, KC_J, KC_Z, LT(2,KC_SPC), LT(3,KC_TAB), LT(5,KC_ENT), LT(4,KC_BSPC)),
    [2] = LAYOUT_split_3x5_2(LSFT(KC_NUHS), RALT(KC_E), RALT(KC_2), LSFT(KC_6), RALT(KC_3), LSFT(KC_3), LSFT(KC_7), LSFT(KC_LBRC), KC_LBRC, KC_SLSH, KC_NUHS, LSFT(KC_1), KC_RBRC, LSFT(KC_MINS), LSFT(KC_5), LSFT(KC_SLSH), KC_COMM, KC_DOT, LSFT(KC_COMM), LSFT(KC_DOT), LSFT(KC_QUOT), LSFT(KC_4), LSFT(KC_RBRC), LSFT(KC_GRV), KC_NO, RALT(KC_LBRC), KC_MINS, KC_EQL, LSFT(KC_EQL), KC_QUOT, KC_NO, KC_NO, TO(3), TO(1)),
    [3] = LAYOUT_split_3x5_2(MYMACRO_MAIL, RALT(KC_E), LSFT(KC_0), LSFT(KC_5), TO(0), LSFT(KC_3), KC_PSLS, KC_PAST, KC_PPLS, KC_PMNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_LSFT, LSFT(KC_4), KC_NO, KC_SPC, KC_DEL, KC_ESC, KC_COMM, KC_DOT, LSFT(KC_DOT), KC_RSFT, KC_SPC, KC_CALC, KC_ENT, KC_BSPC),
    [4] = LAYOUT_split_3x5_2(MYMACRO_OES, MYMACRO_AO, KC_NO, KC_NO, KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NUBS, LSFT(KC_NUBS), LSFT(KC_8), LSFT(KC_9), LSFT(KC_7), KC_GRV, RALT(KC_7), RALT(KC_0), RALT(KC_8), RALT(KC_9), MYMACRO_COES, MYMACRO_CAO, KC_SCLN, LSFT(KC_0), KC_NO, KC_BSPC, LSFT(KC_2), KC_NO, KC_NO, KC_NO, KC_CAPS, KC_NO, KC_NO, KC_NO),
    [5] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_ESC, KC_ESC, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, OS_HYPR, MS_BTN1, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MS_BTN2, MS_LEFT, MS_UP, MS_DOWN, MS_RGHT, KC_NO, KC_NO, KC_NO, KC_NO),
    [6] = LAYOUT_split_3x5_2(KC_PSLS, KC_7, KC_8, KC_9, KC_PAST, KC_PAST, KC_7, KC_8, KC_9, KC_PSLS, KC_PDOT, KC_4, KC_5, KC_6, KC_PPLS, KC_PPLS, KC_4, KC_5, KC_6, KC_BSPC, KC_BSPC, KC_1, KC_2, KC_3, KC_PMNS, KC_PMNS, KC_1, KC_2, KC_3, TO(0), KC_0, KC_ENT, KC_ENT, KC_0),
    [7] = LAYOUT_split_3x5_2(KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_ESC, KC_VOLD, KC_MUTE, KC_VOLU, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_DEL, KC_MRWD, KC_MPLY, KC_MSTP, KC_MFFD, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_WBAK, KC_WREF, KC_WHOM, KC_WFWD, KC_NO, KC_NO, TO(6), KC_CALC),
    [8] = LAYOUT_split_3x5_2(KC_ESC, LCTL(KC_C), LCTL(KC_X), KC_NO, LCTL(KC_S), KC_NO, KC_NO, MS_WHLU, MS_WHLD, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_DEL, KC_NO, KC_RGUI, KC_RALT, KC_RCTL, KC_RSFT, LCTL(KC_V), LCTL(KC_Z), C_S_T(KC_Y), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(9), TO(6), MS_BTN1, MS_BTN2),
    [9] = LAYOUT_split_3x5_2(KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_ESC, KC_NO, KC_UP, KC_NO, KC_DEL, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_LCTL, KC_X, KC_C, KC_V, KC_ENT, TO(0), KC_1, KC_2, KC_3, KC_4, KC_SPC, KC_TAB, KC_ENT, KC_SPC)

};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
        switch (keycode) {
            case MYMACRO_AO:
                if (record->event.pressed) {
                     SEND_STRING(SS_TAP(X_NUHS)SS_TAP(X_A)SS_TAP(X_O));
                }
                break;
            case MYMACRO_OES:
                if (record->event.pressed) {
                     SEND_STRING(SS_TAP(X_NUHS)SS_TAP(X_O)SS_TAP(X_E)SS_TAP(X_S));
                }
                break;
            case MYMACRO_CAO:
                if (record->event.pressed) {
                    SEND_STRING(SS_TAP(X_SCLN)SS_TAP(X_NUHS)SS_TAP(X_A)SS_TAP(X_O));
                }
                break;
            case MYMACRO_COES:
                if (record->event.pressed) {
                    SEND_STRING(SS_TAP(X_SCLN)SS_TAP(X_NUHS)SS_TAP(X_O)SS_TAP(X_E)SS_TAP(X_S));
                }
                break;
            case MYMACRO_MAIL:
                if (record->event.pressed) {
                    send_string_with_delay("rui.alves.peixoto",20);
                    send_string_with_delay(SS_RALT("2"),20);
                    send_string_with_delay("gmail.com",25);
                }
                break;
        }
        return true;
};
