#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
enum custom_keycodes { QK_MYMACRO_0 = SAFE_RANGE, QK_MYMACRO_1, QK_MYMACRO_2, QK_MYMACRO_3 };


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(LT(6,KC_Q), KC_W, KC_F, KC_P, KC_ESC, OSM(MOD_RSFT), KC_L, KC_U, KC_Y, LT(6,KC_K), LSFT_T(KC_A), LCTL_T(KC_R), LALT_T(KC_S), LGUI_T(KC_T), KC_G, KC_M, KC_N, RALT_T(KC_E), RCTL_T(KC_I), RSFT_T(KC_O), LT(2,KC_V), KC_X, KC_C, KC_D, KC_DEL, LCTL(KC_BSPC), KC_H, KC_B, KC_J, LT(5,KC_Z), LT(1,KC_SPC), LT(8,KC_TAB), LT(3,KC_ENT), LT(4,KC_BSPC)),
	[1] = LAYOUT_split_3x5_2(LSFT(KC_NUHS), RALT(KC_E), RALT(KC_2), LSFT(KC_6), RALT(KC_3), LSFT(KC_3), LSFT(KC_7), LSFT(KC_LBRC), KC_LBRC, LT(0,KC_SLSH), KC_NUHS, LSFT(KC_1), KC_RBRC, LSFT(KC_MINS), LSFT(KC_5), LSFT(KC_SLSH), KC_COMM, KC_DOT, LSFT(KC_COMM), LSFT(KC_DOT), LSFT(KC_QUOT), LSFT(KC_4), LSFT(KC_RBRC), LSFT(KC_2), KC_NO, RALT(KC_LBRC), KC_MINS, KC_EQL, LSFT(KC_EQL), KC_QUOT, KC_NO, TG(1), TG(1), KC_NO),
	[2] = LAYOUT_split_3x5_2(KC_PSLS, KC_7, KC_8, KC_9, KC_PAST, KC_PAST, KC_7, KC_8, KC_9, KC_PSLS, KC_PDOT, KC_4, KC_5, KC_6, KC_PPLS, KC_PPLS, KC_4, KC_5, KC_6, KC_PDOT, KC_BSPC, KC_1, KC_2, KC_3, KC_PMNS, KC_PMNS, KC_1, KC_2, KC_3, TG(2), KC_0, KC_ENT, KC_ENT, KC_0),
	[3] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ESC, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN2, KC_MS_L, KC_MS_U, KC_MS_D, KC_MS_R, KC_NO, TG(3), KC_NO, TG(3)),
	[4] = LAYOUT_split_3x5_2(QK_MYMACRO_1, QK_MYMACRO_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NUBS, LSFT(KC_NUBS), LSFT(KC_8), LSFT(KC_9), LSFT(KC_7), KC_GRV, RALT(KC_7), RALT(KC_0), RALT(KC_8), RALT(KC_9), QK_MYMACRO_3, QK_MYMACRO_2, KC_SCLN, LSFT(KC_0), KC_NO, KC_BSPC, LSFT(KC_GRV), KC_NO, KC_NO, KC_NO, KC_NO, TG(4), TG(4), KC_NO),
	[5] = LAYOUT_split_3x5_2(KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_ESC, KC_VOLD, KC_MUTE, KC_VOLU, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_DEL, KC_MRWD, KC_MPLY, KC_MSTP, KC_MFFD, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_WBAK, KC_WREF, KC_WHOM, KC_WFWD, KC_NO, KC_NO, TG(5), KC_CALC),
	[6] = LAYOUT_split_3x5_2(KC_ESC, LCTL(KC_C), LCTL(KC_X), LCTL(KC_V), KC_CAPS, KC_NO, KC_NO, KC_NO, KC_NO, KC_CAPS, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_DEL, KC_NO, KC_RGUI, KC_RALT, KC_RCTL, KC_RSFT, LCTL(KC_V), LCTL(KC_Z), C_S_T(KC_Y), KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_U, KC_WH_D, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_BTN2),
	[7] = LAYOUT_split_3x5_2(KC_TAB, KC_Q, KC_W, KC_E, KC_ESC, KC_NO, KC_NO, TG(7), KC_NO, KC_NO, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_X, KC_C, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, LT(2,KC_E), KC_NO, KC_NO),
	[8] = LAYOUT_split_3x5_2(KC_NO, RALT(KC_E), LSFT(KC_0), LSFT(KC_5), KC_NO, KC_NO, KC_PSLS, KC_PAST, KC_PPLS, KC_PMNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, LSFT(KC_4), KC_NO, KC_SPC, KC_DEL, KC_NO, KC_COMM, KC_DOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, KC_BSPC)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
        switch (keycode) {
            case QK_MYMACRO_0:
                if (record->event.pressed) {
                    SEND_STRING(SS_TAP(X_NUHS)SS_TAP(X_A)SS_TAP(X_O));
                }
                break;
            case QK_MYMACRO_1:
                if (record->event.pressed) {
                    SEND_STRING(SS_TAP(X_NUHS)SS_TAP(X_O)SS_TAP(X_E)SS_TAP(X_S));
                }
                break;
            case QK_MYMACRO_2:
                if (record->event.pressed) {
                    SEND_STRING(SS_TAP(X_SCLN)SS_TAP(X_NUHS)SS_TAP(X_A)SS_TAP(X_O));
                }
                break;
            case QK_MYMACRO_3:
                if (record->event.pressed) {
                    SEND_STRING(SS_TAP(X_SCLN)SS_TAP(X_NUHS)SS_TAP(X_O)SS_TAP(X_E)SS_TAP(X_S));
                }
                break;
        }
        return true;
};



